### ISSUE TITLE
Clarification on project licensing

### ISSUE THREAD

**Issue by billfitzgerald** [mit-teaching-systems-lab/dcss#36]
Hello!

This project doesn't have a license committed in the repository, nor is one visible when looking at the Community Standards page.

![Screenshot from 2023-08-25 15-39-45](https://github.com/mit-teaching-systems-lab/dcss/assets/1602849/077c988b-5efa-4339-8630-75433640c8ee)

I also took a look through the wiki to see if a license was listed there, and didn't see anything.

Could you clarify the licensing of this project by adding a license.txt file (or some equivalent) to the root dir in the repository, and by adding this info into the README,md file?

**Comment by rwaldron** [comment]
https://github.com/mit-teaching-systems-lab/dcss/commit/a231eff6dd9f40966c225fc732d328b637295f5f
