### ISSUE TITLE
Display bug in teachermoments.mit.edu

### ISSUE THREAD

**Issue by billfitzgerald** [mit-teaching-systems-lab/dcss#37]
Hello,

I'm assuming that the site at https://teachermoments.mit.edu is the this deployment: https://github.com/mit-teaching-systems-lab/dcss/deployments/teacher-moments-production

There is a bug that is visible on the home page where, when two (or more?) people have the home page loaded, if one person takes an action in one browser window all other browser windows see the same activity.

This video shows the issue with two browsers (firefox and chrome) and a browser on a phone. The phone and the computer are connected via different internet connections.

https://vimeo.com/858721705/8ef875922a

I have also replicated this with a person across the country during a call.

The video shows how to replicate this.

**Comment by rwaldron** [comment]
That's the weirdest thing I've ever seen. That page is actually hosted elsewhere, as "branded landing page" can be set via environment variable, to point to an arbitrary url. I'm going to look into the landing page code and see what I can learn.

**Comment by billfitzgerald** [comment]
Yeah, it's pretty bizarre. Duplicating the issue with folks while on a video call was pretty entertaining :)
